### ISSUE TITLE
release install fail on Ubuntu because tcl include is in /usr/include/tcl8.6

### ISSUE THREAD

**Issue by johannct** [lsst-camera-dh/release#1]
Is there a reason why the configure script is not left alone to find the right paths in the system, on l.43 of bin/install.py ?

**Comment by heather999** [comment]
I'm not sure.. I similarly see that if I don't update the install script, the build of Modules complains about using the 32bit tcl:
/usr/bin/ld: skipping incompatible /usr/lib/libtcl8.5.so when searching for -ltcl8.5
/usr/bin/ld: skipping incompatible /usr/lib/libdl.so when searching for -ldl
/usr/bin/ld: skipping incompatible /usr/lib/libm.so when searching for -lm
/usr/bin/ld: skipping incompatible /usr/lib/libX11.so when searching for -lX11
/usr/bin/ld: skipping incompatible /usr/lib/libdl.so when searching for -ldl
/usr/bin/ld: skipping incompatible /usr/lib/libm.so when searching for -lm
/usr/bin/ld: skipping incompatible /usr/lib/libX11.so when searching for -lX11
/usr/bin/ld: skipping incompatible /usr/lib/libc.so when searching for -lc
That disappears if I either point at /usr/lib64 during configure, or just ignore it, and let the configure script find the appropriate tcl. I do see in the Modules documentation that you need tcl setup in the PATH.  
Ultimately we won't be installing Modules with every install - rather we'll treat it more like an external library.

**Comment by jchiang87** [comment]
fixed in 3ca2dbb
