### ISSUE TITLE
error: ‘Tcl_Interp’ has no member named ‘errorLine’

### ISSUE THREAD

**Issue by johannct** [lsst-camera-dh/release#2]
I am using TCL 8.6, and this function seems deprecated. One quick way out is to modify l.43 so that it reads 
"CPPFLAGS=\"-DUSE_INTERP_ERRORLINE\" ./configure ....
This is short term though, removing errorLine use is probably better : http://www.gossamer-threads.com/lists/gentoo/dev/266045 for the long term modifs proposal to codes.

**Comment by jchiang87** [comment]
On my laptop, I modified cmdModule.c to use Tcl_SetErrorLine and Tcl_GetErrorLine

http://www.tcl.tk/cgi-bin/tct/tip/336.html
